#type: args

train:
  epochs: 1500
  batch_size: 128
  lr: 0.0005

diffusion:
  layers: 5
  channels: 128
  nheads: 4 
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.1
  num_steps: 500
  schedule: "quad"
 
model:
  weightsemb: 128
  featureemb: 128